---
title: "Data Management Workshop à la CHONe"
output:
  html_document:
    toc: yes
    toc_float: yes
  github_document:
    pandoc_args: --output=README.md
  html_notebook:
    toc: yes
    toc_float: yes
---
#Introduction:
This workshop, in the style of [Software Carpentry](https://software-carpentry.org/) and [Data Carpentry](http://www.datacarpentry.org/) workshops are for any researcher who has data they want to analyze, and no prior computational experience is required. This hands-on workshop teaches basic concepts, skills and tools for working more effectively with data.
We will cover Data organization in spreadsheets, Introduction to R, Data analysis and visualization in R. Participants should bring their laptops and plan to participate actively. By the end of the workshop learners should be able to more effectively manage and analyze data and be able to apply the tools and approaches directly to their ongoing research.

## Requirements:
Participants must bring a laptop with a Mac, Linux, or Windows operating system (not a tablet, Chromebook, etc.) that they have administrative privileges on. They should have a few specific software packages installed (listed below, please install latest version for maximum compatibility).

- [OpenRefine](http://openrefine.org/)OpenRefine (formerly Google Refine) is a powerful tool for working with messy data: cleaning it; transforming it from one format into another. (Download and extract only, no 'install')
- [R](http://cran.utstat.utoronto.ca/) is a language and environment for statistical computing and graphics.
- [RStudio](https://www.rstudio.com/products/RStudio/#Desktop) (the open source 'free' version) is an integrated development environment (IDE) for R. It includes a console, syntax-highlighting editor that supports direct code execution, as well as tools for plotting, history, debugging and workspace management.
- [Github Desktop](https://desktop.github.com/) (the app) is a seamless way to contribute to projects on [GitHub](https://github.com/) (the website)
- [A Github account](https://github.com/join?source=header-home) Will allow you to host your version controlled project folder (repository) in the cloud for collaboration, sharing (and backup!). 

## Objectives:
- Initiate and provide training to participants in organized reproducible data workflow
- Produce a structured data management and archiving plan for individual projects


## Instructors:
- David Beauchesne
- Rémi Daigle
- Angela Grant

## Agenda:
| May 1 | *Four Points Gatineau, Renaissance B, 4th Floor*  |
|--------|-------------------------------------------------------------------------|
|6 - 9 PM  | - [Introduction to Data Workshop](https://remi-daigle.github.io/2017-CHONe-Data/introduction.nb.html) (why?, open access, Angela. <br> - [Metadata](https://remi-daigle.github.io/2017-CHONe-Data/metadata.nb.html) (what is it, standards, Gis, DCT... ) Angela. <br> - [Data organization with spreadsheets](https://remi-daigle.github.io/2017-CHONe-Data/organization.nb.html) (don’t save as excel file, don’t put spaces in columns, square data frame, standard vocab for column headers, Dates). (Remi) <br> - [Data cleaning and raw data management](https://remi-daigle.github.io/2017-CHONe-Data/cleaning.nb.html) (openrefine and other tools, replicable workflow) (Remi/David)  |
 
| May 2 | *Four Points Gatineau, Renaissance B, 4th Floor*  |
|--------|-------------------------------------------------------------------------|
|8:30 AM - Noon | - [Shock and awe with R](https://remi-daigle.github.io/2017-CHONe-Data/shocknawe.nb.html) (Remi/David) <br> - [Text analysis](https://remi-daigle.github.io/2017-CHONe-Data/text.nb.html)   (David/Remi) <br> - [Data Analysis and Visualization in R](https://remi-daigle.github.io/2017-CHONe-Data/dataviz.nb.html) (basic dplyr, tidyverse, spatial mapping with (http://remi-daigle.github.io/GIS_mapping_in_R/) (Remi/David)|
|Noon - 1 PM | - Lunch |
| 1 - 5 | - [Data Archiving & version control](https://remi-daigle.github.io/2017-CHONe-Data/versioncontrol.nb.html) ( Angela: review of data repositories (zenodo, figshare, dryad, OBIS, Remi/David: version control, student builder pack, Github) |
| evening | - Hacky Hour (everyone) |